name: deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
  TF_VAR_SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.ROLE_ARN_GITHUB_ACTION_SSM_DEPLOY_ROLE }}
          aws-region: ap-northeast-1
      - run: terraform init
      - run: terraform plan

